version: '3.9'

services:
  dev:
    image: sistema-agendamento
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll=2000"]
